# Generated by Django 6.0.6 on 2026-06-07 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_auth', '0002_profile_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='affiliate_code',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True, verbose_name='Affiliate Code'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='approved_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Approved At'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='role',
            field=models.CharField(choices=[('admin', 'Admin'), ('provider', 'Provider'), ('affiliate', 'Affiliate')], default='provider', max_length=10, verbose_name='Role'),
        ),
    ]
