# Generated by Django 6.0.6 on 2026-06-07 19:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_auth', '0003_userprofile_affiliate_code_userprofile_approved_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='parent_affiliate',
            field=models.ForeignKey(blank=True, help_text='The affiliate who created this semi-affiliate account', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='semi_affiliates', to='user_auth.userprofile', verbose_name='Parent Affiliate'),
        ),
    ]
