# Generated by Django 6.0.6 on 2026-06-07 21:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_auth', '0004_userprofile_parent_affiliate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='role',
            field=models.CharField(choices=[('admin', 'Admin'), ('provider', 'Provider'), ('affiliate', 'Affiliate'), ('semi_affiliate', 'Semi-Affiliate'), ('professional_client', 'Professional Client'), ('final_client', 'Final Client')], default='provider', max_length=20, verbose_name='Role'),
        ),
    ]
