# Generated by Django 5.2.5 on 2026-06-19 14:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0019_order_affiliate_share_order_loft_share_and_more'),
        ('user_auth', '0006_wallet_transaction'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='source_product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transaction_sources', to='dashboard.product', verbose_name='Source Product'),
        ),
        migrations.AddField(
            model_name='transaction',
            name='source_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sourced_transactions', to=settings.AUTH_USER_MODEL, verbose_name='Source User'),
        ),
    ]
