# Generated by Django 5.2.5 on 2026-06-19 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_auth', '0007_transaction_source_product_transaction_source_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='quantity',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Quantity'),
        ),
        migrations.AddField(
            model_name='transaction',
            name='unit_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Unit Price (DZD)'),
        ),
    ]
