# Generated by Django 5.2.5 on 2026-07-26 07:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_auth', '0008_transaction_quantity_transaction_unit_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='created_by',
            field=models.ForeignKey(blank=True, help_text='The semi-affiliate who created this end client account', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='end_clients', to='user_auth.userprofile', verbose_name='Created By'),
        ),
    ]
