# Generated by Django 5.2.5 on 2026-06-02 06:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=255, verbose_name='Full Name')),
                ('phone_number', models.CharField(max_length=50, verbose_name='Phone Number')),
                ('project_type', models.CharField(max_length=100, verbose_name='Project Type')),
                ('message', models.TextField(verbose_name='Message')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Contact Request',
                'verbose_name_plural': 'Contact Requests',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SiteSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Site Settings',
                'verbose_name_plural': 'Site Settings',
            },
        ),
        migrations.AddField(
            model_name='portfolio',
            name='is_featured',
            field=models.BooleanField(default=False, verbose_name='Is Featured'),
        ),
        migrations.AddField(
            model_name='product',
            name='is_featured',
            field=models.BooleanField(default=False, verbose_name='Is Featured'),
        ),
        migrations.AddField(
            model_name='product',
            name='quantity',
            field=models.PositiveIntegerField(default=1, verbose_name='Available Quantity'),
        ),
        migrations.CreateModel(
            name='SiteSettingsSliderImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='settings/slider/', verbose_name='Slider Image')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('settings', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='slider_images', to='dashboard.sitesettings', verbose_name='Settings')),
            ],
            options={
                'verbose_name': 'Site Settings Slider Image',
                'verbose_name_plural': 'Site Settings Slider Images',
                'ordering': ['created_at'],
            },
        ),
    ]
