# Generated by Django 5.2.5 on 2026-06-02 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dashboard", "0002_contactrequest_sitesettings_order_quantity_and_more"),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.AddField(
                    model_name="order",
                    name="quantity",
                    field=models.PositiveIntegerField(default=1, verbose_name="Quantity"),
                ),
            ],
            database_operations=[],
        ),
    ]
