# Generated by Django 5.2.5 on 2026-06-04 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0004_cart_cartitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='model_3d',
            field=models.FileField(blank=True, help_text='Upload GLB or GLTF 3D model file', null=True, upload_to='products/models/', verbose_name='3D Model'),
        ),
    ]
