# Generated by Django 5.2.5 on 2026-06-05 19:08

import django.db.models.deletion
from django.db import migrations, models


def migrate_orders_to_checkout(apps, schema_editor):
    Order = apps.get_model("dashboard", "Order")
    CheckoutOrder = apps.get_model("dashboard", "CheckoutOrder")
    for order in Order.objects.all():
        items = getattr(order, "items", None)
        if items is None:
            items = []
        if isinstance(items, str):
            import json
            try:
                items = json.loads(items)
            except (json.JSONDecodeError, TypeError):
                items = []
        items = items or []
        CheckoutOrder.objects.create(
            items=items or [],
            customer_name=order.customer_name,
            customer_phone=order.customer_phone,
            customer_address=order.customer_address,
            wilaya=order.wilaya,
            commune=order.commune,
            status=order.status,
            created_at=order.created_at,
        )


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0008_remove_order_product_remove_order_quantity_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CheckoutOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('items', models.JSONField(blank=True, default=list, help_text='List of products in this order with title, price, quantity, thumbnail', verbose_name='Order Items')),
                ('customer_name', models.CharField(max_length=255, verbose_name='Customer Name')),
                ('customer_phone', models.CharField(max_length=20, verbose_name='Phone Number')),
                ('customer_address', models.TextField(blank=True, verbose_name='Address')),
                ('wilaya', models.CharField(blank=True, max_length=100, verbose_name='Wilaya')),
                ('commune', models.CharField(blank=True, max_length=100, verbose_name='Commune')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='pending', max_length=20, verbose_name='Status')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Checkout Order',
                'verbose_name_plural': 'Checkout Orders',
                'ordering': ['-created_at'],
            },
        ),
        migrations.RunPython(migrate_orders_to_checkout, migrations.RunPython.noop),
        migrations.RemoveField(
            model_name='order',
            name='items',
        ),
        migrations.AddField(
            model_name='order',
            name='product',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to='dashboard.product', verbose_name='Product'),
        ),
        migrations.AddField(
            model_name='order',
            name='quantity',
            field=models.PositiveIntegerField(default=1, verbose_name='Quantity'),
        ),
    ]
