# Generated by Django 5.2.5 on 2026-06-05 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0009_checkoutorder_remove_order_items_order_product_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CheckoutOrder',
        ),
        migrations.RemoveField(
            model_name='order',
            name='product',
        ),
        migrations.RemoveField(
            model_name='order',
            name='quantity',
        ),
        migrations.AddField(
            model_name='order',
            name='items',
            field=models.JSONField(blank=True, default=list, help_text='List of products in this order with title, price, quantity, thumbnail', verbose_name='Order Items'),
        ),
    ]
