# Generated by Django 6.0.6 on 2026-06-07 19:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0010_delete_checkoutorder_remove_order_product_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='loft_purchase_price',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Price the supplier expects from Loft Design', max_digits=10, verbose_name='Purchase Price (DZD)'),
        ),
        migrations.AddField(
            model_name='product',
            name='loft_retail_price',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Default retail price for end clients (set by admin)', max_digits=10, null=True, verbose_name='Retail Price (DZD)'),
        ),
        migrations.AddField(
            model_name='product',
            name='loft_wholesale_price',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Default wholesale price for affiliates (set by admin)', max_digits=10, null=True, verbose_name='Wholesale Price (DZD)'),
        ),
        migrations.AddField(
            model_name='product',
            name='rejection_reason',
            field=models.TextField(blank=True, verbose_name='Rejection Reason'),
        ),
        migrations.AddField(
            model_name='product',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=20, verbose_name='Status'),
        ),
        migrations.CreateModel(
            name='PartnerPrice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Custom Price (DZD)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('buyer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prices_as_buyer', to=settings.AUTH_USER_MODEL, verbose_name='Buyer')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='partner_prices', to='dashboard.product', verbose_name='Product')),
                ('seller', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prices_as_seller', to=settings.AUTH_USER_MODEL, verbose_name='Seller')),
            ],
            options={
                'verbose_name': 'Partner Price',
                'verbose_name_plural': 'Partner Prices',
                'unique_together': {('product', 'seller', 'buyer')},
            },
        ),
    ]
