# Generated by Django 6.0.6 on 2026-06-08 09:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0011_product_loft_purchase_price_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='partnerprice',
            name='price',
        ),
        migrations.RemoveField(
            model_name='product',
            name='price',
        ),
        migrations.AddField(
            model_name='order',
            name='buyer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders_as_buyer', to=settings.AUTH_USER_MODEL, verbose_name='Buyer'),
        ),
        migrations.AddField(
            model_name='order',
            name='order_number',
            field=models.CharField(blank=True, max_length=30, null=True, unique=True, verbose_name='Order Number'),
        ),
        migrations.AddField(
            model_name='order',
            name='seller',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders_as_seller', to=settings.AUTH_USER_MODEL, verbose_name='Seller'),
        ),
        migrations.AddField(
            model_name='partnerprice',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Active'),
        ),
        migrations.AddField(
            model_name='partnerprice',
            name='purchase_price',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Price the buyer pays the seller', max_digits=10, verbose_name='Purchase Price (DZD)'),
        ),
        migrations.AddField(
            model_name='partnerprice',
            name='retail_price',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Price at which buyer can resell (retail)', max_digits=10, null=True, verbose_name='Retail Price (DZD)'),
        ),
        migrations.AddField(
            model_name='partnerprice',
            name='wholesale_price',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Price at which buyer can resell (wholesale)', max_digits=10, null=True, verbose_name='Wholesale Price (DZD)'),
        ),
        migrations.AddField(
            model_name='product',
            name='brand',
            field=models.CharField(blank=True, max_length=255, verbose_name='Brand'),
        ),
        migrations.AddField(
            model_name='product',
            name='sku',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True, verbose_name='SKU'),
        ),
        migrations.AlterField(
            model_name='order',
            name='items',
            field=models.JSONField(blank=True, default=list, help_text='List of products with title, price, quantity, thumbnail at time of order', verbose_name='Order Items'),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('confirmed', 'Confirmed'), ('paid', 'Paid'), ('delivered', 'Delivered'), ('cancelled', 'Cancelled')], default='pending', max_length=20, verbose_name='Status'),
        ),
        migrations.CreateModel(
            name='LoftPrice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('loft_purchase_price', models.DecimalField(decimal_places=2, help_text='Copied from supplier price at approval time', max_digits=10, verbose_name='Loft Purchase Price (DZD)')),
                ('loft_default_wholesale_price', models.DecimalField(decimal_places=2, help_text='Default price for affiliates buying from Loft', max_digits=10, verbose_name='Default Wholesale Price (DZD)')),
                ('loft_retail_price', models.DecimalField(decimal_places=2, help_text='Public retail price for end clients', max_digits=10, verbose_name='Retail Price (DZD)')),
                ('is_active', models.BooleanField(default=True, verbose_name='Active')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('product', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='loft_price', to='dashboard.product', verbose_name='Product')),
            ],
            options={
                'verbose_name': 'Loft Price',
                'verbose_name_plural': 'Loft Prices',
            },
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1, verbose_name='Quantity')),
                ('unit_price', models.DecimalField(decimal_places=2, help_text='Price applied at time of order', max_digits=10, verbose_name='Unit Price (DZD)')),
                ('total_price', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Total Price (DZD)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_items', to='dashboard.order', verbose_name='Order')),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='order_items', to='dashboard.product', verbose_name='Product')),
            ],
            options={
                'verbose_name': 'Order Item',
                'verbose_name_plural': 'Order Items',
            },
        ),
        migrations.CreateModel(
            name='SupplierPrice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('loft_purchase_price', models.DecimalField(decimal_places=2, help_text='Price Loft Design pays the supplier', max_digits=10, verbose_name='Loft Purchase Price (DZD)')),
                ('suggested_retail_price', models.DecimalField(blank=True, decimal_places=2, help_text="Supplier's suggested retail price", max_digits=10, null=True, verbose_name='Suggested Retail Price (DZD)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('product', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='supplier_price', to='dashboard.product', verbose_name='Product')),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='supplier_prices', to=settings.AUTH_USER_MODEL, verbose_name='Supplier')),
            ],
            options={
                'verbose_name': 'Supplier Price',
                'verbose_name_plural': 'Supplier Prices',
            },
        ),
    ]
