# Generated by Django 5.2.5 on 2026-06-08 09:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0012_remove_partnerprice_price_remove_product_price_and_more'),
    ]

    operations = [
        migrations.RunSQL(
            "ALTER TABLE dashboard_product DROP COLUMN IF EXISTS commission_rate;",
            migrations.RunSQL.noop,
        ),
    ]
