# Generated by Django 5.2.5 on 2026-06-09 20:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0013_remove_commission_rate'),
        ('user_auth', '0005_alter_userprofile_role'),
    ]

    operations = [
        migrations.CreateModel(
            name='AffiliateStore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('store_name', models.CharField(blank=True, max_length=255, verbose_name='Store Name')),
                ('store_logo', models.ImageField(blank=True, upload_to='stores/logos/', verbose_name='Store Logo')),
                ('store_banner', models.ImageField(blank=True, upload_to='stores/banners/', verbose_name='Store Banner')),
                ('store_description', models.TextField(blank=True, verbose_name='Store Description')),
                ('header_bg_color', models.CharField(default='#1a1a2e', max_length=7, verbose_name='Header Background Color')),
                ('is_active', models.BooleanField(default=True, verbose_name='Active')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('affiliate', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='store', to='user_auth.userprofile', verbose_name='Affiliate')),
            ],
            options={
                'verbose_name': 'Affiliate Store',
                'verbose_name_plural': 'Affiliate Stores',
            },
        ),
        migrations.CreateModel(
            name='StoreVisit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('visitor_ip', models.GenericIPAddressField(blank=True, null=True, verbose_name='Visitor IP')),
                ('session_key', models.CharField(blank=True, max_length=40, verbose_name='Session')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='store_visits', to='dashboard.product', verbose_name='Product')),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='visits', to='dashboard.affiliatestore', verbose_name='Store')),
            ],
            options={
                'verbose_name': 'Store Visit',
                'verbose_name_plural': 'Store Visits',
                'ordering': ['-created_at'],
            },
        ),
    ]
