# Generated by Django 5.2.5 on 2026-06-09 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0014_affiliatestore_storevisit'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='referred_by',
            field=models.CharField(blank=True, help_text='Affiliate code that referred this order', max_length=30, verbose_name='Referred By'),
        ),
    ]
