# Generated by Django 5.2.5 on 2026-06-12 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0017_order_commission_paid'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='show_in_global_store',
            field=models.BooleanField(default=True, help_text='Uncheck to hide this product from the public storefront', verbose_name='Show in Global Store'),
        ),
    ]
