# Generated by Django 5.2.5 on 2026-06-18 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0018_product_show_in_global_store'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='affiliate_share',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text="Affiliate's profit from this order", max_digits=12, verbose_name='Affiliate Share'),
        ),
        migrations.AddField(
            model_name='order',
            name='loft_share',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text="Loft Design's profit from this order", max_digits=12, verbose_name='Loft Share'),
        ),
        migrations.AddField(
            model_name='order',
            name='semi_share',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text="Semi-affiliate's profit from this order", max_digits=12, verbose_name='Semi-Affiliate Share'),
        ),
        migrations.AddField(
            model_name='order',
            name='supplier_share',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Amount paid to supplier for this order', max_digits=12, verbose_name='Supplier Share'),
        ),
        migrations.AddField(
            model_name='partnerprice',
            name='allocated_stock',
            field=models.PositiveIntegerField(default=0, help_text='Quantity allocated from master stock to this buyer', verbose_name='Allocated Stock'),
        ),
        migrations.AddField(
            model_name='partnerprice',
            name='sold_stock',
            field=models.PositiveIntegerField(default=0, help_text='Running count of units sold through this price record', verbose_name='Sold Stock'),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('store_validated', 'Store Validated'), ('admin_validated', 'Admin Validated'), ('supplier_fulfilling', 'Supplier Fulfilling'), ('shipped', 'Shipped'), ('delivered', 'Delivered'), ('cancelled', 'Cancelled')], default='pending', max_length=20, verbose_name='Status'),
        ),
    ]
