# Generated by Django 5.2.5 on 2026-06-19 16:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0019_order_affiliate_share_order_loft_share_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='partnerprice',
            name='allocated_stock',
        ),
        migrations.RemoveField(
            model_name='partnerprice',
            name='sold_stock',
        ),
    ]
