# Generated by Django 5.2.5 on 2026-06-23 20:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0021_alter_order_status'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PriceHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('field_name', models.CharField(help_text='e.g. loft_purchase_price, loft_wholesale, loft_retail, partner_wholesale, partner_retail', max_length=100, verbose_name='Price Field')),
                ('old_value', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Old Value (DZD)')),
                ('new_value', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='New Value (DZD)')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Changed At')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='price_history', to='dashboard.product', verbose_name='Product')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='price_changes', to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'verbose_name': 'Price History',
                'verbose_name_plural': 'Price Histories',
                'ordering': ['-created_at'],
            },
        ),
    ]
