# Generated by Django 6.0.6 on 2026-06-30 11:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0023_productitem_productitemimage'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='show_in_admin_store',
            field=models.BooleanField(default=False, help_text="Check to feature this product in the admin's storefront", verbose_name='Show in Admin Store'),
        ),
        migrations.CreateModel(
            name='AdminStore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('store_name', models.CharField(blank=True, max_length=255, verbose_name='Store Name')),
                ('store_logo', models.ImageField(blank=True, upload_to='stores/logos/', verbose_name='Store Logo')),
                ('store_banner', models.ImageField(blank=True, upload_to='stores/banners/', verbose_name='Store Banner')),
                ('store_description', models.TextField(blank=True, verbose_name='Store Description')),
                ('header_bg_color', models.CharField(default='#1a1a2e', max_length=7, verbose_name='Header Background Color')),
                ('is_active', models.BooleanField(default=True, verbose_name='Active')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='admin_store', to=settings.AUTH_USER_MODEL, verbose_name='Admin')),
            ],
            options={
                'verbose_name': 'Admin Store',
                'verbose_name_plural': 'Admin Stores',
            },
        ),
    ]
