# Generated by Django 5.2.5 on 2026-07-28 06:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0024_admin_store_and_field'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='portfoliogallery',
            name='portfolio',
        ),
        migrations.DeleteModel(
            name='Portfolio',
        ),
        migrations.DeleteModel(
            name='PortfolioGallery',
        ),
    ]
