# Generated by Django 6.0.6 on 2026-06-30 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0024_admin_store_and_field'),
    ]

    operations = [
        migrations.AddField(
            model_name='adminstore',
            name='slug',
            field=models.SlugField(blank=True, help_text="Custom URL for your store (e.g. 'loft-collection'). Can only be set once.", max_length=100, null=True, unique=True, verbose_name='Store URL Slug'),
        ),
        migrations.AddField(
            model_name='adminstore',
            name='slug_changed',
            field=models.BooleanField(default=False, verbose_name='Slug Set'),
        ),
    ]
