# Generated by Django 5.2.5

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0025_remove_portfoliogallery_portfolio_delete_portfolio_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='supplierprice',
            name='affiliate_wholesale_price',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Price the provider charges its own affiliates when reselling this product', max_digits=10, null=True, verbose_name='Affiliate Wholesale Price (DZD)'),
        ),
        migrations.AddField(
            model_name='order',
            name='provider_share',
            field=models.DecimalField(decimal_places=2, default=0.00, help_text="Provider's network profit (provider_wholesale - supplier_base) from this order", max_digits=12, verbose_name='Provider Share'),
        ),
    ]
