# Generated by Django 5.2.5 on 2026-10-01 23:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dashboard", "0026_supplierprice_affiliate_wholesale_price_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="currency",
            field=models.CharField(
                default="DZD",
                help_text="Currency shown to the customer (EUR for visitors outside Algeria)",
                max_length=3,
                verbose_name="Currency",
            ),
        ),
        migrations.AddField(
            model_name="order",
            name="total_eur",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                max_digits=12,
                null=True,
                verbose_name="Total (EUR)",
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="price_eur",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Shown to visitors outside Algeria. Leave empty to show the DZD price.",
                max_digits=10,
                null=True,
                verbose_name="Price (EUR, outside Algeria)",
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="pro_price",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Price for approved professional clients buying directly. Leave empty to use the retail price.",
                max_digits=10,
                null=True,
                verbose_name="Professional Price (DZD)",
            ),
        ),
    ]
