# Generated by Django 5.2.5 on 2026-10-02 11:45

import hashlib

from django.db import migrations, models


def fill_existing(apps, schema_editor):
    ProductAsset = apps.get_model("dashboard", "ProductAsset")
    for asset in ProductAsset.objects.all().iterator():
        try:
            digest = hashlib.sha256()
            with asset.file.open("rb") as f:
                for chunk in f.chunks():
                    digest.update(chunk)
            asset.sha256, asset.file_size = digest.hexdigest(), asset.file.size
        except (OSError, ValueError):
            continue  # file missing on this server: leave it empty
        asset.save(update_fields=["sha256", "file_size"])


class Migration(migrations.Migration):

    dependencies = [
        ("dashboard", "0029_bpid_variants_manufacturer"),
    ]

    operations = [
        migrations.AddField(
            model_name="productasset",
            name="compatibility",
            field=models.CharField(
                blank=True,
                help_text="Software and minimum version, e.g. SketchUp 2021+, Revit 2022+.",
                max_length=120,
                verbose_name="Compatibility",
            ),
        ),
        migrations.AddField(
            model_name="productasset",
            name="file_size",
            field=models.PositiveBigIntegerField(
                default=0, editable=False, verbose_name="File size (bytes)"
            ),
        ),
        migrations.AddField(
            model_name="productasset",
            name="polygon_count",
            field=models.PositiveIntegerField(
                blank=True, null=True, verbose_name="Polygons"
            ),
        ),
        migrations.AddField(
            model_name="productasset",
            name="scale",
            field=models.CharField(default="1:1", max_length=20, verbose_name="Scale"),
        ),
        migrations.AddField(
            model_name="productasset",
            name="sha256",
            field=models.CharField(
                blank=True, editable=False, max_length=64, verbose_name="SHA-256"
            ),
        ),
        migrations.AddField(
            model_name="productasset",
            name="unit",
            field=models.CharField(
                choices=[
                    ("mm", "Millimetres"),
                    ("cm", "Centimetres"),
                    ("m", "Metres"),
                    ("in", "Inches"),
                ],
                default="mm",
                max_length=2,
                verbose_name="Unit",
            ),
        ),
        migrations.RunPython(fill_existing, migrations.RunPython.noop),
    ]
