# Generated by Django 5.2.5 on 2026-10-02 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dashboard", "0030_asset_metadata"),
    ]

    operations = [
        migrations.AddField(
            model_name="adminstore",
            name="i18n",
            field=models.JSONField(
                blank=True, default=dict, verbose_name="Translations"
            ),
        ),
        migrations.AddField(
            model_name="affiliatestore",
            name="i18n",
            field=models.JSONField(
                blank=True, default=dict, verbose_name="Translations"
            ),
        ),
        migrations.AddField(
            model_name="category",
            name="i18n",
            field=models.JSONField(
                blank=True, default=dict, verbose_name="Translations"
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="i18n",
            field=models.JSONField(
                blank=True, default=dict, verbose_name="Translations"
            ),
        ),
        migrations.AddField(
            model_name="productitem",
            name="i18n",
            field=models.JSONField(
                blank=True, default=dict, verbose_name="Translations"
            ),
        ),
    ]
