# Generated by Django 5.2.5 on 2026-10-02 11:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("dashboard", "0030_asset_metadata"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ShoppingList",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "code",
                    models.CharField(
                        editable=False, max_length=12, unique=True, verbose_name="Code"
                    ),
                ),
                ("edit_key", models.CharField(editable=False, max_length=40)),
                ("name", models.CharField(max_length=120, verbose_name="Project name")),
                (
                    "client_name",
                    models.CharField(blank=True, max_length=120, verbose_name="Client"),
                ),
                (
                    "budget",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=14,
                        null=True,
                        verbose_name="Total budget (DZD)",
                    ),
                ),
                (
                    "bilnov_project_id",
                    models.CharField(
                        blank=True, max_length=64, verbose_name="BILNOV project ID"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            ("shared", "Shared"),
                            ("approved", "Approved"),
                            ("ordered", "Ordered"),
                        ],
                        default="draft",
                        max_length=10,
                        verbose_name="Status",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "owner",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="shopping_lists",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Owner",
                    ),
                ),
            ],
            options={
                "verbose_name": "Shopping list",
                "verbose_name_plural": "Shopping lists",
                "ordering": ["-updated_at"],
            },
        ),
        migrations.CreateModel(
            name="Room",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=80, verbose_name="Room")),
                (
                    "budget",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=14,
                        null=True,
                        verbose_name="Budget (DZD)",
                    ),
                ),
                ("position", models.PositiveIntegerField(default=0)),
                (
                    "shopping_list",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="rooms",
                        to="shopping.shoppinglist",
                    ),
                ),
            ],
            options={
                "verbose_name": "Room",
                "verbose_name_plural": "Rooms",
                "ordering": ["position", "pk"],
            },
        ),
        migrations.CreateModel(
            name="ShoppingListItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "quantity",
                    models.PositiveIntegerField(default=1, verbose_name="Quantity"),
                ),
                ("title_snapshot", models.CharField(max_length=255)),
                ("bpid_snapshot", models.CharField(blank=True, max_length=24)),
                ("variant_id_snapshot", models.CharField(blank=True, max_length=32)),
                (
                    "price_snapshot",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=12,
                        null=True,
                        verbose_name="Price when added (DZD)",
                    ),
                ),
                (
                    "price_eur_snapshot",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=12, null=True
                    ),
                ),
                ("snapshot_at", models.DateTimeField(auto_now_add=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("proposed_client", "Proposed by the client"),
                            ("proposed_architect", "Proposed by the architect"),
                            ("to_discuss", "To discuss"),
                            ("accepted", "Accepted"),
                            ("refused", "Refused"),
                            ("replaced", "Replaced"),
                            ("integrated", "Integrated in the design"),
                            ("validated", "Final validation"),
                        ],
                        default="proposed_client",
                        max_length=20,
                        verbose_name="Status",
                    ),
                ),
                (
                    "note",
                    models.CharField(blank=True, max_length=255, verbose_name="Note"),
                ),
                ("position", models.PositiveIntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "added_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="dashboard.product",
                    ),
                ),
                (
                    "replaced_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="replaces",
                        to="shopping.shoppinglistitem",
                    ),
                ),
                (
                    "room",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="items",
                        to="shopping.room",
                        verbose_name="Room",
                    ),
                ),
                (
                    "shopping_list",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="items",
                        to="shopping.shoppinglist",
                    ),
                ),
                (
                    "variant",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="dashboard.productitem",
                    ),
                ),
            ],
            options={
                "verbose_name": "List item",
                "verbose_name_plural": "List items",
                "ordering": ["position", "pk"],
            },
        ),
    ]
